### ISSUE TITLE
few offerings

### ISSUE THREAD

**Issue by Viste** [Qblolz/TrinityWeb#3]
- add posibiliti to add reCaptcha to auth and registration forms(helps with bots ins almost all cases)
- add banned players list

**Comment by Qblolz** [comment]
reCaptcha - will be realise in v2.0
List of banned players - its possible, but action to ban/unban player without soap connection - i think it`s  impossible.

**Comment by Viste** [comment]
Need only list of players who banned and reason its all

**Comment by Tyrelis** [comment]
I think that should be added for admin panel. Like you said above ban/unban with soap.

**Comment by Qblolz** [comment]
I'll think about it, but I've been told a lot by people - try to avoid soap

**Comment by Viste** [comment]
SOAP is hole in you ass )

**Comment by Tyrelis** [comment]
Not if you dumb and don't know how to protect it correctly.

**Comment by Qblolz** [comment]
Any code example "how not todo" ? I want see any code with SOAP and after i need sometime to think

**Comment by luisforte** [comment]
Qblolz... does TrinityWeb works on AzerothCore ?

**Comment by Qblolz** [comment]
> Qblolz... does TrinityWeb works on AzerothCore ?
If database structure like TrinityCore database - i think yes, but need test it then i realise v2.0 with Installing module (GUI)

**Comment by luisforte** [comment]
![image](https://user-images.githubusercontent.com/20118021/39264182-a5c24530-489a-11e8-9962-de985841b1d3.png)

I will tell you... i use last AzerothCore and need a working Store NOW....

**Comment by Viste** [comment]
works on sunwell with some fixes so Azeroth not a trouble

**Comment by Qblolz** [comment]
added reCaptcha
